apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: fraudsterslist
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: fraudsterslist
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: fraudsterslist/mongo_uri
