apiVersion: v1
kind: Service
metadata:
  name: fraudsterslist-backend-service
  namespace: fraudsterslist
spec:
  selector:
    app: fraudsterslist-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
